artifact_uri: file:///C:/Users/sfennelly/Documents/Anthem/Asset/mlruns/0/34c6404b2da0490c8e712b8b59e5552b/artifacts
end_time: 1646873452151
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 34c6404b2da0490c8e712b8b59e5552b
run_uuid: 34c6404b2da0490c8e712b8b59e5552b
source_name: ''
source_type: 4
source_version: ''
start_time: 1646786533260
status: 3
tags: []
user_id: sfennelly
